add some basic functions for dealing with urls add isinarray function change default of doover to true unzip files in subdatasets

diff --git a/share/generic/file.bash.in b/share/generic/file.bash.in
--- a/share/generic/file.bash.in
+++ b/share/generic/file.bash.in
@@ -42,42 +42,66 @@ function dozip_multiband {
     local i=0
     local files
     local msband
-
-    for msband in "${msbands[@]}"
+    
+    ##### loop over the subdataset array #####
+    
+    if [[ ${#subdsnames[@]} == 0 ]]
+    then
+        local subdsnames=( "" )
+    fi
+    local sub
+    for sub in "${subdsnames[@]}"
     do
-        local regex="${msband//./[.]}"
-        local regex="${regex//\*/.*}"
-        local regex="${regex//\?/.}"
+        local tmp
+        eval tmp=\( \$\{msbands$sub\[@\]\} \)
+        local mymsbands=( "${tmp[@]}" )
+        unset tmp
+        local tmp
+        eval tmp=\"\$panband$sub\"
+        local mypanband="$tmp"
+        unset tmp
+        for msband in "${msbands[@]}"
+        do
+            local regex="${msband//./[.]}"
+            local regex="${regex//\*/.*}"
+            local regex="${regex//\?/.}"
 
-        if grep -i -e "$regex" <<<"$zipinfo" > /dev/null
+            if grep -i -e "$regex" <<<"$zipinfo" > /dev/null
+            then
+                local bandfile="$(grep -i -e "$regex" <<<"$zipinfo" | head -n 1)"
+                if ! isinarray "$bandfile" "${files[@]}"
+                then
+                    files[i++]="$bandfile"
+                fi
+            else
+                echo "ERROR: no match in zip for \"$msband\""
+                return;
+            fi
+        
+        done
+    
+        ##### find the pan band #####
+        ##### fixme this only assumes 1 posible panband #####
+        
+        local panfiles
+        if [ -n "$panband" ]
         then
-            files[i++]="$(grep -i -e "$regex" <<<"$zipinfo" | head -n 1)"
-        else
-            echo "ERROR: no match in zip for \"$msband\""
-            return;
+            
+            local regex="${panband//./[.]}"
+            local regex="${regex//\*/.*}"
+            local regex="${regex//\?/.}"
+            
+            if grep -i -e "$regex" <<<"$zipinfo" > /dev/null
+            then
+                panfiles[0]="$(grep -i -e "$regex" <<<"$zipinfo" | head -n 1)"
+            else
+                echo "ERROR: no match in zip for \"$panband\""
+                return;
+            fi
         fi
     
     done
     
-    ##### find the pan band #####
-    
-    local panfiles
-    if [ -n "$panband" ]
-    then
-        
-        local regex="${panband//./[.]}"
-        local regex="${regex//\*/.*}"
-        local regex="${regex//\?/.}"
-        
-        if grep -i -e "$regex" <<<"$zipinfo" > /dev/null
-        then
-            panfiles[0]="$(grep -i -e "$regex" <<<"$zipinfo" | head -n 1)"
-        else
-            echo "ERROR: no match in zip for \"$panband\""
-            return;
-        fi
-    fi
-        
     ##### extract the files #####
         
     unzip "${origdir}/${zipfile}" \
