document generic bash code, rerun doxygen

diff --git a/share/generic/file.bash.in b/share/generic/file.bash.in
--- a/share/generic/file.bash.in
+++ b/share/generic/file.bash.in
@@ -19,13 +19,30 @@
 # FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 # DEALINGS IN THE SOFTWARE.
 
-have_hdf="@HAVE_HDF@"
+
+have_hdf="@HAVE_HDF@";
+
+
 
 ###############################################################################
-# function to process a zip in a multiband case
+## @brief function to process a zip in a multiband case
+##
+## @param zipfile    zip file its assumed to be in origdir
+## @param tmpdir     temp dir to store output in
+## @param ts         timestamp of the current file
+## @param origdir    dir the original files are in
+##
+## @return 0 on success, 1 on fail
+##
+## @details
+## global vars
+## @param subdsnames  array of subdsnames
+## @param msbands     arrays of band filename patterns to use
+## @param panband     panban panband filename pattern to use
+##
 ###############################################################################
 
-function dozip_multiband {
+dozip_multiband () {
 
     local zipfile="$1"
     local tmpdir="$2"
@@ -45,7 +62,7 @@ function dozip_multiband {
     local msband
     
     ##### loop over the subdataset array #####
-    
+    # FIXME add mask bands
     if [[ ${#subdsnames[@]} == 0 ]]
     then
         local subdsnames=( "" )
@@ -115,10 +132,24 @@ function dozip_multiband {
 }
 
 ###############################################################################
-# function to process a tar in a multiband case
+## @brief function to process a tar in a multiband case
+##
+## @param zipfile    tar file its assumed to be in origdir
+## @param tmpdir     temp dir to store output in
+## @param ts         timestamp of the current file
+## @param origdir    dir the original files are in
+##
+## @return 0 on success, 1 on fail
+##
+## @details
+## global vars
+## @param subdsnames  array of subdsnames
+## @param msbands     arrays of band filename patterns to use
+## @param panband     panban panband filename pattern to use
+##
 ###############################################################################
 
-function dotar_multiband {
+dotar_multiband () {
 
     local zipfile="$1"
     local tmpdir="$2"
@@ -152,7 +183,7 @@ function dotar_multiband {
     zipinfo="$(tar -t${switch}f "${origdir}/${zipfile}")"
 
     ##### for now we just assume tiff, id like to make this better later #####
-    
+    #FIXME add mask bands
     local i=0
     local files
     ##### loop over the subdataset array #####
@@ -228,12 +259,19 @@ function dotar_multiband {
 }
 
 ###############################################################################
-# function to take a list of files on stdin and make a bash array declaration
-# script of files with the same basename in each array
-# this produces one local array per line named files
-###############################################################################'
+## @brief function to take a list of files on stdin and make a bash array declaration
+## script of files with the same basename in each array
+## this produces one local array per line named files
+##
+## @param ext    the extension on the files to mach associated files to
+## @param stdin  PIPE of files names to search
+##
+## note this function creates bash arrays that are outputed to stdout to be
+## eval by the calling function
+## 
+###############################################################################
 
-function find_asoc_files {
+find_asoc_files () {
     ext=$1
     
     awk -v "ext=$ext" '
@@ -287,12 +325,18 @@ END {
 }
 
 ###############################################################################
-# function to take a list of files on stdin and make a bash array declaration
-# script of files with the same basename in each array
-# this produces one local array per line named files
-###############################################################################'
+## @brief function to take a list of files on stdin and make a bash array declaration
+## script of files with the same basename in each array
+## this produces one local array per line named files
+## @param ext    the extension on the files to mach associated files to
+## @param stdin  PIPE of files names to search
+##
+## note this function creates bash arrays that are outputed to stdout to be
+## eval by the calling function
+## 
+###############################################################################
 
-function find_asoc_shape_files {
+find_asoc_shape_files () {
     ext=$1
     
     awk -v "ext=$ext" '
@@ -347,10 +391,23 @@ END {
 
 
 ###############################################################################
-# function to process a gzip file
+## @brief function to process a gzip file
+##
+## @param zipfile    gzip file its assumed to be in origdir
+## @param tmpdir     temp dir to store output in
+## @param ts         timestamp of the current file
+## @param origdir    dir the original files are in
+##
+## @return 0 on success, 1 on fail
+##
+## @details
+## global vars
+## @param vector
+## @param msbands
+##   
 ###############################################################################
 
-function dogzip {
+dogzip () {
     local zipfile="$1"
     local tmpdir="$2"
     local ts="$3"
@@ -392,11 +449,24 @@ function dogzip {
 
 }
 
-################################################################################
-# function to process a gzip file
+###############################################################################
+## @brief function to process a bzip file
+##
+## @param zipfile    bzip file its assumed to be in origdir
+## @param tmpdir     temp dir to store output in
+## @param ts         timestamp of the current file
+## @param origdir    dir the original files are in
+##
+## @return 0 on success, 1 on fail
+##
+## @details
+## global vars
+## @param vector
+## @param msbands
+##   
 ###############################################################################
 
-function dobzip {
+dobzip () {
     local zipfile="$1"
     local tmpdir="$2"
     local ts="$3"
@@ -438,10 +508,24 @@ function dobzip {
 
 
 ###############################################################################
-# function to process a zip file
+## @brief function to process a zip file
+##
+## @param zipfile    zip file its assumed to be in origdir
+## @param tmpdir     temp dir to store output in
+## @param ts         timestamp of the current file
+## @param origdir    dir the original files are in
+##
+## @return 0 on success, 1 on fail
+##
+## @details
+## global vars
+## @param vector
+## @param msbands
+## @param extglob
+##   
 ###############################################################################
 
-function dozip {
+dozip () {
     local zipfile="$1"
     local tmpdir="$2"
     local ts="$3"
@@ -581,10 +665,24 @@ function dozip {
 }
 
 ###############################################################################
-# function to process a tar.gz file
+## @brief function to process a tar.gz file
+##
+## @param zipfile    tar file its assumed to be in origdir
+## @param tmpdir     temp dir to store output in
+## @param ts         timestamp of the current file
+## @param origdir    dir the original files are in
+##
+## @return 0 on success, 1 on fail
+##
+## @details
+## global vars
+## @param vector
+## @param msbands
+## @param extglob
+##   
 ###############################################################################
 
-function dotar {
+dotar () {
     local zipfile="$1"
     local tmpdir="$2"
     local ts="$3"
@@ -747,10 +845,18 @@ function dotar {
 }
 
 ###############################################################################
-# function to process a kmz file
+## @brief function to process a kmz file
+##
+## @param zipfile    kmzfile its assumed to be in origdir
+## @param tmpdir     temp dir to store output in
+## @param ts         timestamp of the current file
+## @param origdir    dir the original files are in
+##
+## @return 0 on success, 1 on fail
+##
 ###############################################################################
 
-function dokmz {
+dokmz () {
     local zipfile="$1"
     local tmpdir="$2"
     local ts="$3"
@@ -808,10 +914,27 @@ function dokmz {
 
 
 ###############################################################################
-# function loop over the subdataset array and call a callback function
+## @brief function loop over the subdataset array and call a callback function
+##
+## @param cbfunc     callback function
+## @param cbargs     array of args to pass to the callback function
+##
+## @return 0 on success, 1 on fail of the callback
+##
+## @details
+## global vars
+## @param subdsnames      array of subdsnames
+## @param msbands*        arrays of band filename patterns
+## @param msmaskbands*    array of mask bands
+## @param mspreproc_lut*  lut to scale bands with before any other proccessing
+## @param panband*        panban panband filename pattern
+## @param mscalc*         ITK calculation to build a product
+## @param lut*            lut to recale output
+## @param msgradient*     gradient to colorize single band image
+##   
 ###############################################################################
 
-function subds_iterator {
+subds_iterator () {
     local cbfunc="$1"
     local cbargs=("${@:2}")
     
@@ -874,19 +997,19 @@ function subds_iterator {
 }
     
 ###############################################################################
-# function to get the pan band from an array of files
+## @brief function to get the pan band from an array of files
+##
+## @param files      array of files to search
+##
+## @details
+## global vars
+## @param panband*        panban panband filename pattern
+##
 ###############################################################################
 
-function findpan_cb {
-    local files=("${@:1}")
-    
-    if [ -n "$panband" ]
-    then
-        find_band_file "$panband" "${files[@]}" || { printerror ; return; }
-    fi
-}
 
-function findpan {
+
+findpan () {
     local files=("${@:1}")
     
     ##### find the pan band #####
@@ -896,11 +1019,36 @@ function findpan {
     
 }
 
+findpan_cb () {
+    local files=("${@:1}")
+    
+    if [ -n "$panband" ]
+    then
+        find_band_file "$panband" "${files[@]}" || { printerror ; return; }
+    fi
+}
+
 ###############################################################################
-# function to get the basename of a ms file
+## @brief function to get the basename of a set of ms files
+##
+## @param files      array of files to search
+##
+## @details
+## global vars
+## @param msbands*        arrays of band filename patterns
+##
 ###############################################################################
 
-function getms_base_cb {
+getms_base () {
+    local files=("${@:1}")
+    
+    ##### find the base name #####
+
+    subds_iterator "getms_base_cb" "${files[@]}" | head -n 1
+    
+}
+
+getms_base_cb () {
     local files=("${@:1}")
     
     if [ -n "$panband" ]
@@ -913,21 +1061,21 @@ function getms_base_cb {
     fi
 }
 
-function getms_base {
-    local files=("${@:1}")
-    
-    ##### find the pan band #####
-    ##### FIXME this only assumes 1 posible panband #####
-    
-    subds_iterator "getms_base_cb" "${files[@]}" | head -n 1
-    
-}
 
 ###############################################################################
-# function to decide howto deal with a file
+## @brief function to decide howto deal with a file
+##
+## @param file       main file to proccess
+## @param ext        extension of the main file
+## @param tmpdir     temp dir to use for proccessing
+## @param ts=        timestamp of this file
+## @param origdir    dir all files are assumed to be in
+## @param files      array of the file and its asociated files
+##
+## 
 ###############################################################################
 
-function dofile_sub {
+dofile_sub () {
     local file="$1"
     local ext="$2"
     local tmpdir="$3"
@@ -1036,10 +1184,29 @@ function dofile_sub {
 }
 
 ###############################################################################
-# function to proccess a file
+## @brief function to proccess a file
+## 
+## @param myline     line from a ftp mirror file or a url for NewEarthExplorer
+##
+## @details
+## global vars
+## @param indir                   dir the original file(s) will be placed in
+## @param outdir                  dir to place the output in
+## @param NewEarthExplorer_user   username for the NewEarthExplorer login if this is
+##                            set myline is assumed to be a NewEarthExplorer url
+## @param DWH_REBUILD             flag to say if were in rebuild mode -rebuild
+## @param tmp                     the temp dir
+## @param ignoredir               flag to ignore ignore the sub dir name files are
+##                            placed in
+## @param DEBUG_dofile            flag to print out debug info and return
+## @param subdsnames              array of subdsnames
+##
+## note this function echoes to fd 3 when finished and is called by mainloop
+## multi proccesseing
+##
 ###############################################################################
 
-function dofile {
+dofile () {
     myline=$1
 
     local sourcedir=${indir//\/\///}
@@ -1054,7 +1221,7 @@ function dofile {
     }
     
     ##### new earth explorer #####
-    
+    #FIXME add error checking
     if [ -n "$NewEarthExplorer_user" ] && ! istrue "$DWH_REBUILD"
     then
         local file
diff --git a/share/generic/msimage.bash.in b/share/generic/msimage.bash.in
--- a/share/generic/msimage.bash.in
+++ b/share/generic/msimage.bash.in
@@ -19,13 +19,20 @@
 # FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 # DEALINGS IN THE SOFTWARE.
 
-have_otb="@HAVE_OTB@"
+have_otb="@HAVE_OTB@";
 
 ###############################################################################
-# function to write a vrt to rescale with a lut
+## @brief function to write a vrt to rescale with a lut
+##
+## @param infile    full path to the input file
+## @param outvrt    full path to the vrt to create
+## @param lut       the lut
+##
+## @return 0 for success, 1 for failure
+##
 ###############################################################################
 
-function mk_lut_vrt {
+mk_lut_vrt () {
     local infile="$1"
     local outvrt="$2"
     local lut="$3"
@@ -76,10 +83,17 @@ EOF
 
 
 ###############################################################################
-# function to build a 3 band vrt out of a 1 band image with a gradient
+## @brief function to build a 3 band vrt out of a 1 band image with a gradient
+##
+## @param infile    full path to the input file
+## @param outvrt    full path to the vrt to create
+## @param gradient  the gradient
+##
+## @return 0 for success, 1 for failure
+##
 ###############################################################################
 
-function mk_gradient_vrt {
+mk_gradient_vrt () {
     local infile="$1"
     local outvrt="$2"
     local gradient="$3"
@@ -162,12 +176,18 @@ EOF
 
 
 ###############################################################################
-# function to build a 3 band vrt out of a 1 band image
+## @brief function to build a 3 band vrt out of a 1 band image
+##
+## @param infile    full path to the input file
+## @param outvrt    full path to the vrt to create
+##
+## @return 0 for success, 1 for failure
+##
 ###############################################################################
 
-function mk_3of1_vrt {
-    in=$1
-    out=$2
+mk_3of1_vrt () {
+    infile=$1
+    outvrt=$2
     
     ##### make a temp dir #####
     
@@ -176,15 +196,15 @@ function mk_3of1_vrt {
     
     ##### build a temp vrt to get most of our info from #####
 
-    gdal_translate -of VRT "$in" "${tmpdir}/mk_3of1_vrt.vrt" || { printerror ; return; }
+    gdal_translate -of VRT "$infile" "${tmpdir}/mk_3of1_vrt.vrt" || { printerror ; return; }
     
     ##### get the band type #####
     
-    local type=$(get_band_type "$in" 1)
+    local type=$(get_band_type "$infile" 1)
 
     keep=$(sed "${tmpdir}/mk_3of1_vrt.vrt" -e 's:</VRTDataset>::')
     
-    cat > "$out" << EOF
+    cat > "$outvrt" << EOF
 $keep
   <VRTRasterBand dataType="$type" band="2">
   </VRTRasterBand>
@@ -196,10 +216,19 @@ EOF
 }
 
 ###############################################################################
-# function to build a single mask vrt out of an array of masks
+## @brief function to build a single mask vrt out of an array of masks
+##
+## @param base      products basename
+## @param tmpdir    the dir to create the files in
+## @param masks     the array of masks to and together
+##
+## @return 0 for success, 1 for failure
+##
+## @retval stdout the full path to the final output file
+##
 ###############################################################################
 
-function combine_masks {
+combine_masks () {
     local base="$1"
     local tmpdir="$2"
     local masks=("${@:3}")
@@ -243,11 +272,21 @@ function combine_masks {
 }
 
 ###############################################################################
-# function to make an array of files with tmpdir prefixed that match
-# the msbands array
+## @brief function to make an array of files with tmpdir prefixed that match
+##        the msbands array
+##
+## @param tmpdir        dir the files are in
+## @param nummsbands    number of msbands 
+## @param msbands       array of mabands
+## @param files         array of filenames
+##
+## @return 0 for success
+##
+## @retval stdout the array of files with tmpdir prefixed
+##
 ###############################################################################
 
-function ms2tmpfiles {
+ms2tmpfiles () {
     local tmpdir="$1"
     local nummsbands="$2"
     local msbands=( "${@:3:$2}" )
@@ -278,10 +317,19 @@ function ms2tmpfiles {
 }
 
 ###############################################################################
-# function to make an array of files that match the msbands array
+## @brief function to make an array of files that match the msbands array
+##
+## @param nummsbands    number of msbands 
+## @param msbands       array of mabands
+## @param files         array of filenames
+##
+## @return 0 for success
+##
+## @retval stdout the array of files
+##
 ###############################################################################
 
-function ms2files {
+ms2files () {
     local nummsbands="$1"
     local msbands=( "${@:2:$1}" )
     local files=( "${@:$((2+$1))}" )
@@ -310,10 +358,23 @@ function ms2files {
 }
 
 ###############################################################################
-# function to fill nodata
+## @brief function to fill nodata
+##
+## @param base      products basename
+## @param tmpdir    the dir to create the files in
+## @param file      full path to the input file
+##
+## @return 0 for success, 1 for failure
+##
+## @retval stdout the full path to the final output file
+##
+## @detail
+## global vars
+## @param fillnodata_md  the maxdistance to search for valid values to fill with
+##
 ###############################################################################
 
-function fillnodata {
+fillnodata () {
     local base="$1"
     local tmpdir="$2"
     local file="$3"
@@ -354,10 +415,26 @@ function fillnodata {
 }
 
 ###############################################################################
-# function mscalc
+## @brief function to run otb calc to do band math
+##
+## @param base      products basename
+## @param tmpdir    the dir to create the files in
+## @param file      full path to the input file
+##
+## @return 0 for success, 1 for failure
+##
+## @retval stdout the full path to the final output file
+##
+## @detail
+## global vars
+## @param mscalc*       the ITK math to use with otbcalc
+## @param msgradient*   the gradient to scale the output with if set
+## 
+## if msgradient is not set the result will be a black and white image (3 bands)
+##
 ###############################################################################
 
-function mscalc {
+mscalc () {
     local base="$1"
     local tmpdir="$2"
     local file="$3"
@@ -396,10 +473,20 @@ function mscalc {
 }
 
 ###############################################################################
-# function to pansharpen an image
+## @brief function to pansharpen an image
+##
+## @param base      products basename
+## @param tmpdir    the dir to create the files in
+## @param panfile   the panfile to sharpen with
+## @param file      full path to the input file
+##
+## @return 0 for success, 1 for failure
+##
+## @retval stdout the full path to the final output file
+##
 ###############################################################################
 
-function pansharpen {
+pansharpen () {
     local base="$1"
     local tmpdir="$2"
     local panfile="$3"
@@ -441,10 +528,20 @@ function pansharpen {
 }
 
 ###############################################################################
-# function to make a rgb image and a band image into a rgba vrt
+## @brief function to make a rgb image and a band image into a rgba vrt
+##
+## @param base      products basename
+## @param tmpdir    the dir to create the files in
+## @param img_rgb   full path to the rgb image
+## @param img_a     full path to the rgb band
+##
+## @return 0 for success, 1 for failure
+##
+## @retval stdout the full path to the final output file
+#
 ###############################################################################
 
-function combine_rgb_a {
+combine_rgb_a () {
     local base="$1"
     local tmpdir="$2"
     local img_rgb="$3"
@@ -487,14 +584,27 @@ function combine_rgb_a {
 }
 
 ###############################################################################
-# function to proccess a multiband image
+## @brief function to preproccess bands with a lut
+##
+## @param base      products basename
+## @param tmpdir    the dir to find the the input files in
+## @param newtmpdir the dir to place the output files in
+##
+## @return 0 for match, 1 for no match
+##
+## @retval stdout the full path to the final output files
+##
+## @detail
+## global vars
+## @param mspreproc_lut*  lut to scale bands with before any other proccessing
+##
 ###############################################################################
 
-function preproc_lut {
+preproc_lut () {
     local base="$1"
     local tmpdir="$2"
     local newtmpdir="$3"
-    local file="$4"
+
     
     for ((i = 0; i < "${#mspreproc_lut[@]}"  ; i += 2))
     do
@@ -514,10 +624,17 @@ function preproc_lut {
 }
 
 ###############################################################################
-#function to print out a list of color switches for a washout nearblack
+## @brief function to print out a list of color switches for a washout nearblack
+##
+## @param numbands      number of bands
+##
+## @return 0 for success
+##
+## @retval stdout the list of color switches
+##
 ###############################################################################
 
-function washout_switches {
+washout_switches () {
     local numbands=$1
     
     for ((i = 0 ; i < $(bc <<< "2^${numbands}") - 1 ; i++ ))
@@ -528,13 +645,22 @@ function washout_switches {
 }
 
 ###############################################################################
-# function to do a washout nearblack
+## @brief function to do a washout nearblack
+##
+## @param base      products basename
+## @param tmpdir    the dir to create the files in
+## @param file      full path to the input file
+##
+## @return 0 for success, 1 for failure
+##
+## @retval stdout the final output files with no path
+##
 ###############################################################################
 
-function washout_nearblack {
+washout_nearblack () {
     local base="$1"
-    local file="$2"
-    local tmpdir="$3"
+    local tmpdir="$2"
+    local file="$3"
 
  
     local numbands
@@ -565,14 +691,36 @@ function washout_nearblack {
 }
         
 ###############################################################################
-# function to proccess a multiband image
+## @brief callback function to proccess a multiband image
+##
+## @param base          products basename
+## @param tmpdir        the dir the files are in
+## @param ts            timestamp of this item
+## @param isoriginal    flag to mark the image as original file
+##                            (dont delete = true)
+## @param panfile       the panfile to sharpen with
+## @param files         array of files
+##
+## @return 0 for success, 1 for failure
+##
+## @details
+## global vars
+## @param subdsnames      array of subdsnames
+## @param msbands*        arrays of band filename patterns
+## @param msmaskbands*    array of mask bands
+## @param mspreproc_lut*  lut to scale bands with before any other proccessing
+## @param panband*        panban panband filename pattern
+## @param mscalc*         ITK calculation to build a product
+## @param lut*            lut to recale output
+## @param msgradient*     gradient to colorize single band image
+##   
 ###############################################################################
 
 #FIXME panfile should just be in the file array and we should sort it out in this function
 # this will make other code easyer
 # there should be a function to get a list of all msbands, msmasks, mspans
 
-function doimg_multiband_cb {
+doimg_multiband_cb () {
 
     local base="$1"
     local tmpdir="$2"
@@ -750,7 +898,7 @@ function doimg_multiband_cb {
     if [[ "$type" != "Byte" ]] && ! istrue "$nearwhite"
     then
         
-        if wash=$( washout_nearblack "$base" "$originalfile" "${newtmpdir}") 
+        if wash=$( washout_nearblack "$base" "${newtmpdir}" "$originalfile" ) 
         then
 
             ##### add the alpha band vrt to the masks array #####
@@ -786,8 +934,33 @@ function doimg_multiband_cb {
     rm -r "$newtmpdir"
 
 }
+###############################################################################
+## @brief main function to proccess a multiband image
+##
+## @param base          products basename
+## @param tmpdir        the dir the files are in
+## @param ts            timestamp of this item
+## @param isoriginal    flag to mark the image as original file
+##                            (dont delete = true)
+## @param panfile       the panfile to sharpen with
+## @param files         array of files
+##
+## @return 0 for success, 1 for failure
+##
+## @details
+## global vars
+## @param subdsnames      array of subdsnames
+## @param msbands*        array of band filename patterns
+## @param msmaskbands*    array of mask bands
+## @param mspreproc_lut*  lut to scale bands with before any other proccessing
+## @param panband*        panban panband filename pattern
+## @param mscalc*         ITK calculation to build a product
+## @param lut*            lut to recale output
+## @param msgradient*     gradient to colorize single band image
+##  
+###############################################################################
 
-function doimg_multiband {
+doimg_multiband () {
     
     subds_iterator "doimg_multiband_cb" "$@"
 
diff --git a/share/generic/newearthexplorer.bash.in b/share/generic/newearthexplorer.bash.in
--- a/share/generic/newearthexplorer.bash.in
+++ b/share/generic/newearthexplorer.bash.in
@@ -22,11 +22,26 @@
 
  
 ###############################################################################
-# function to follow redirects on new earth explorer
-#
+## @brief recursive function to follow redirects on new earth explorer
+##
+## @param url       url to return if no redirect
+## @param referer   last url to pass as referer
+## @param tmpdir    dir to save output in
+## @param headers   header file
+## @param cookie    cookie file
+## @param outfile   output file
+##
+## @return 0 for success
+##
+## @retval stdout the lastlocation redirected to
+##
+## @details
+## global vars
+## @param curl_std_args a standard set of arguments for curl
+##
 ###############################################################################
 
-function NEE_redirect {
+NEE_redirect () {
     local url="$1"
     local referer="$2"
     local tmpdir="$3"
@@ -102,13 +117,31 @@ function NEE_redirect {
 }
 
 ###############################################################################
-# function to log into new earth explorer
-#
-# vars NewEarthExplorer_user NewEarthExplorer_pass must be set
-#
+## @brief function to log into new earth explorer
+##
+## @param url       url to connect to
+## @param referer   last url to pass as referer
+## @param tmpdir    dir to save output in
+## @param oldcookie last coockie file
+## @param cookie    cookie file
+## @param headers   header file
+## @param outfile   output file
+##
+## @return 0 for success 1 for failure
+##
+## @retval stdout the lastlocation redirected to
+##
+## @details
+## global vars
+## @param curl_std_args         a standard set of arguments for curl
+## @param NewEarthExplorer_user username for login
+## @param NewEarthExplorer_pass password for login
+##
+## vars NewEarthExplorer_user NewEarthExplorer_pass must be set
+##
 ###############################################################################
 
-function NEE_login {
+NEE_login () {
     local url="$1"
     local referer="$2"
     local tmpdir="$3"
@@ -146,10 +179,27 @@ function NEE_login {
 }
 
 ###############################################################################
-# function std curl call with a recursive redirect
+## @brief function std curl call with a recursive redirect
+##
+## @param url       url to connect to
+## @param referer   last url to pass as referer
+## @param tmpdir    dir to save output in
+## @param oldcookie last coockie file
+## @param cookie    cookie file
+## @param headers   header file
+## @param outfile   output file
+##
+## @return 0 for success 1 for failure
+##
+## @retval stdout the lastlocation redirected to
+##
+## @details
+## global vars
+## @param curl_std_args         a standard set of arguments for curl
+##
 ###############################################################################
 
-function NEE_curl {
+NEE_curl () {
     local url="$1"
     local referer="$2"
     local tmpdir="$3"
@@ -196,17 +246,28 @@ function NEE_curl {
 
 
 ###############################################################################
-# main function to get a file from new earth explorer
-#
-# vars NewEarthExplorer_user NewEarthExplorer_pass must be set
-#
-# usage: NewEarthExplorer_get "<url> <outdir>
-# http://edcsns17.cr.usgs.gov/NewEarthExplorer/order/process?node=RS&dataset_name=LANDSAT_ETM_SLC_OFF&ordered=LE71270312011259EDC00
+## @brief main function to get a file from new earth explorer
+##
+## @param url       url for the file
+## @param outdir    output dir
+##
+## @return 0 for success 1 for failure
+##
+## @details
+## global vars
+## @param NewEarthExplorer_user username for login
+## @param NewEarthExplorer_pass password for login
+##
+## vars NewEarthExplorer_user NewEarthExplorer_pass must be set
+##
+## usage: NewEarthExplorer_get "<url> <outdir>
+## @n http://edcsns17.cr.usgs.gov/NewEarthExplorer/order/process?node=RS&dataset_name=LANDSAT_ETM_SLC_OFF&ordered=LE71270312011259EDC00
+##
 ###############################################################################
 
-function NewEarthExplorer_get {
+NewEarthExplorer_get () {
     local url="$1"
-    local oldtmpdir="$2"
+    local outdir="$2"
     
     local urlenc="$(url_encode "$url")"
     
@@ -230,7 +291,7 @@ function NewEarthExplorer_get {
         --header "Connection: keep-alive" )
 
     local tmpdir
-    tmpdir=$(mktemp -d -p "${oldtmpdir}" "${dsname}XXXXXXXXXX") #|| { printerror "create tmpdir" ; return 1 }
+    tmpdir=$(mktemp -d -p "${outdir}" "${dsname}XXXXXXXXXX") #|| { printerror "create tmpdir" ; return 1 }
     
 
     ##### get the login page #####
@@ -338,7 +399,7 @@ function NewEarthExplorer_get {
             outfile=$(grep "${tmpdir}/download.header" -e filename= |\
                       sed 's/.*filename=//' |\
                       tr -d "\r" )
-            mv "${tmpdir}/download.out" "$outfile"
+            mv "${tmpdir}/download.out" "${outdir}/$outfile"
             
             echo "$outfile"
         fi
