rework otbPanSharp to use the gdal band type detection add generic multiband code add istrue function for testing vars use the new multiband code for landsat 7

diff --git a/share/generic/file.bash.in b/share/generic/file.bash.in
--- a/share/generic/file.bash.in
+++ b/share/generic/file.bash.in
@@ -19,8 +19,74 @@
 # FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 # DEALINGS IN THE SOFTWARE.
 
+###############################################################################
+# function to process a zip in a multiband case
+###############################################################################
 
+function dozip_multiband {
 
+    local zipfile="$1"
+    local tmpdir="$2"
+    local ts="$3"
+    local origdir="$4"
+    
+    local file="${zipfile##*/}"
+    local base="${file%.*}"
+    
+    local zipinfo="$(zipinfo -1 "${origdir}/${zipfile}")"
+
+    ##### for now we just assume tiff, id like to make this better later #####
+    
+    local i=0
+    local files
+    local msband
+
+    for msband in "${msbands[@]}"
+    do
+        local regex="${msband//./[.]}"
+        local regex="${regex//\*/.*}"
+        local regex="${regex//\?/.}"
+
+        if grep -i -e "$regex" <<<"$zipinfo" > /dev/null
+        then
+            files[i++]="$(grep -i -e "$regex" <<<"$zipinfo" | head -n 1)"
+        else
+            echo "ERROR: no match in zip for \"$msband\""
+            return;
+        fi
+    
+    done
+    
+    ##### find the pan band #####
+    
+    local panfiles
+    if [ -n "$panband" ]
+    then
+        
+        local regex="${panband//./[.]}"
+        local regex="${regex//\*/.*}"
+        local regex="${regex//\?/.}"
+        
+        if grep -i -e "$regex" <<<"$zipinfo" > /dev/null
+        then
+            panfiles[0]="$(grep -i -e "$regex" <<<"$zipinfo" | head -n 1)"
+        else
+            echo "ERROR: no match in zip for \"$panband\""
+            return;
+        fi
+    fi
+        
+    ##### extract the files #####
+        
+    unzip "${origdir}/${zipfile}" \
+           ${files[@]} \
+           ${panfiles[@]} \
+           -d "$tmpdir" > /dev/null 2> /dev/null || return
+    
+    doimg_multiband "$base" "$tmpdir" "$ts" "no" "${panfiles[0]}" ${files[@]}
+    
+}
+    
 ###############################################################################
 # function to process a zip file
 ###############################################################################
@@ -31,6 +97,14 @@ function dozip {
     local ts="$3"
     local origdir="$4"
     
+    ##### check if it is suposed to be multiband #####
+    
+    if [ -n "$msbands" ]
+    then
+        dozip_multiband "$zipfile" "$tmpdir" "$ts" "$origdir"
+        return
+    fi
+        
     zipinfo="$(zipinfo -1 "${origdir}/${zipfile}")"
     
     ##### if exglob is set get a list of those files #####
@@ -505,4 +579,3 @@ function dofile {
     return $status
     
 }
-
